# appveyor config
# based on https://www.appveyor.com/docs/appveyor-yml/
# validated with https://ci.appveyor.com/tools/validate-yaml

version: "{build}"

environment:
  matrix:
    - nodejs_version: "8.9"
    - nodejs_version: "9"

# fix line endings in Windows
init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
  - yarn lerna bootstrap

build: off

cache:
  - node_modules -> yarn.lock

test_script:
  - yarn prettier --list-different
  - yarn test
  - yarn test:e2e

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
