# This is a basic workflow to help you get started with Actions

name: Version NPM package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#on:
#  pull_request:
#    types: [labeled, unlabeled, opened, edited, syncronize]
#    branches: [ master ]
on:
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:
  release:
    name: "Release if we have a version label"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

    - name: Get Version Label
      uses: actions-ecosystem/action-release-label@v1.2.0
      id: version-label
      with:
        # A prefix for labels that indicate semver level ({major, minor, patch}).#
        label_prefix: version-

    - name: Debug Release Label
      run: |
        echo "${{ toJson(github.event.pull_request.labels) }}"
        echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
        echo "${{ github.event.pull_request.merged }}"
      
    #- name: NPM Version #test
    #  if: ${{ steps.version-label.outputs.level != null }}
    #  
    #  run: |
    #    echo "::error PR's to master with a 'version-*' label require a 'release' label"
    #    exit 1
